export const INIT = '@@INIT';

export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED';
export const CONNECTION_UPDATED = 'CONNECTION_UPDATED';

export const TOKEN_BALANCES_LOADED = 'TOKEN_BALANCES_LOADED';

export const SHOW_CONNECTOR_MODAL = 'SHOW_CONNECTOR_MODAL';

export const START_LOADING_PRICES = 'START_LOADING_PRICES';
export const PRICES_LOADED = 'PRICES_LOADED';

export const START_LOADING_USER_TOKENS = 'START_LOADING_USER_TOKENS';
export const USER_TOKENS_LOADED = 'USER_TOKENS_LOADED';

export const VAULTS_LOADED = 'VAULTS_LOADED';

export const TOKEN_LIST_LOADED = 'TOKEN_LIST_LOADED';
export const FETCH_TOKEN_LIST = 'FETCH_TOKEN_LIST';

export const SET_TOKEN = 'SET_TOKEN';
export const SET_VAULT = 'SET_VAULT';

export const SET_DEPOSIT_AMOUNT = 'SET_DEPOSIT_AMOUNT';
export const SET_WITHDRAWAL_AMOUNT = 'SET_WITHDRAWAL_AMOUNT';

export const SET_EXCHANGE_RATE = 'SET_EXCHANGE_RATE';
export const UPDATE_PRICES = 'UPDATE_PRICES';
