export const INIT = '@@INIT';

export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED';
export const CONNECTION_UPDATED = 'CONNECTION_UPDATED';

export const TOKEN_BALANCES_LOADED = 'TOKEN_BALANCES_LOADED';

export const SHOW_CONNECTOR_MODAL = 'SHOW_CONNECTOR_MODAL';

export const START_LOADING_PRICES = 'START_LOADING_PRICES';
export const PRICES_LOADED = 'PRICES_LOADED';

export const START_LOADING_USER_TOKENS = 'START_LOADING_USER_TOKENS';
export const USER_TOKENS_LOADED = 'USER_TOKENS_LOADED';

export const VAULTS_LOADED = 'VAULTS_LOADED';

export const TOKEN_LIST_LOADED = 'TOKEN_LIST_LOADED';
export const FETCH_TOKEN_LIST = 'FETCH_TOKEN_LIST';

export const SELECT_TOKEN = 'SELECT_TOKEN';
